---
kind: Service
apiVersion: v1
metadata:
  name: wordpress-clusterip-service
  # annotations:
  #   service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    # service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/wp-login.php"
spec:
  type: ClusterIP
  selector:
    app: usermgmt-webapp-wordpress
  ports:
    - port: 80
      targetPort: 80